# Meta Data for SEO

## Homepage
title = "MySpace"
titleSeparator = "-"
titleAddition = "Modern Documentation Theme"
description = "MySpace is a hitzhangjie's personal space, for blogs, books, journey, thinkings."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "hitzhangjie"
twitterCreator = "hitzhangjie"
facebookAuthor = "hitzhangjie"
facebookPublisher = "hitzhangjie"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/hitzhangjie"
schemaLinkedIn = "https://www.linkedin.com/in/hitzhangjie/"
schemaGitHub = "https://github.com/hitzhangjie"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/hitzhangjie/myspace/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/hitzhangjie/myspace"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false

[blog]
  # render blog list in style: card-list/simple-list
  style = "simple-list" 
